import random 
from tkinter import*
from PIL import Image, ImageTk
import os

absolute_path = r'C:\Users\Fahima\Desktop\images\ ' # your absolute path goes here(Note: Don't remove the extra space in the end) 

anime = {
"1 Ore ga Ojousama Gakkou ni “Shomin Sample” Toshite Gets♥Sareta Ken": '1.jpg',
"Ookami to Koushinryou II": '2.jpg',
"Ookami to Koushinryou": '3.jpg', 
"Grisaia no Kajitsu": '4.jpeg',
"Nyanko Days": '5.jpeg',
"6 Suzumiya Haruhi no Shoushitsu": '6.jpeg',
"7 Ookami Kodomo no Ame to Yuki": '7.jpeg',
"8 Sankarea": '8.jpg',
"9 Boku no Hero Academia the Movie 2: Heroes Rising": '9.png',
"10 Tensei shitara Slime Datta Ken OVA": '10.jpeg',
"11 Nakitai Watashi wa Neko wo Kaburu ": '11.jpeg', 
"12 Tensei shitara Slime Datta Ken": '12.jpeg',
"13 Nande Koko ni Sensei ga!?": '13.jpeg', 
"14 Kotonoha no Niwa": '14.jpeg', 
"15 Chuunibyou demo Koi ga Shitai! Movie: Take On Me": '15.jpg', 
"16 Byousoku 5 Centimeter": '16.jpeg',
"17 Summer Wars": '17.jpg',
"18 Tenki no Ko ": '18.jpeg',
"19 Kimi no Na wa.": '19.jpeg', 
"20 Sword Art Online: Alicization – War of Underworld": '20.jpg',
"21 Hinamatsuri": '21.jpg',
"22 Gakuen Babysitters ": '22.jpeg',
"23 Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku": '23.jpg',
"24 Yahari Ore no Seishun Love Comedy wa Machigatteiru.": '24.jpg',
"25 Hataraku Maou-sama!": '25.jpeg',   
"26 Shokugeki no Souma: Shin no Sara": '26.jpg',
"27 Shokugeki no Souma: San no Sara – Toutsuki Ressha-hen": '27.jpg',
"28 Sewayaki Kitsune no Senko-san": '28.jpg',
"29 Shokugeki no Souma: San no Sara": '29.jpg',
"30 Shokugeki no Souma: Ni no Sara": '30.jpeg',
"31 Shokugeki no Soma ": '31.jpeg',
"32 Ao no Exorcist ": '32.jpg',
"33 Ao no Exorcist: Kyoto Fujouou-hen": '33.jpg',
"34 Boku dake ga Inai Machi": '34.jpeg',
"35 Kono Subarashii Sekai ni Shukufuku wo!: Kurenai Densetsu": '35.jpg',
"36 Hyouka": '36.jpeg',
"37 Kami no Tou": '37.jpg',
"38 Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e": '38.png',
"39 Shingeki no Kyojin Season 3": '39.jpg',
"40 Kaguya-sama wa Kokurasetai?: Tensai-tachi no Renai Zunousen 2nd Season": '40.jpeg',
"41 Shingeki no Kyojin Season 3 Part 2": '41.jpg',
"42 Shingeki no Kyojin Season 2": '42.jpg',
"43 Shingeki no Kyojin ": '43.jpg',
"44 Kono Subarashii Sekai ni Shukufuku wo! 2": '44.jpg',
"45 Seishun Buta Yarou wa Yumemiru Shoujo no Yume wo Minai": '45.jpeg',
"46 Kono Subarashii Sekai ni Shukufuku wo!": '46.jpeg',
"47 Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai": '47.jpg',
"48 Sakurasou no Pet na Kanojo": '48.jpg',
"49 Tate no Yuusha no Nariagari": '49.jpeg',
"50 IS: Infinite Stratos": '50.jpeg',
"51 Kawaikereba Hentai demo Suki ni Natte Kuremasu ka?": '51.png',
"52 Enen no Shouboutai": '52.jpeg',
"53 Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen": '53.jpg',
"54 Chuunibyou demo Koi ga Shitai! Ren": '54.jpg',
"55 Koe no Katachi ": '55.jpg',
"56 Dr. Stone": '56.jpg',
"57 One Punch Man": '57.jpeg',
"58 Naruto Shippuden": '58.jpeg', 
"59 Sword Art Online II": '59.jpeg',
"60 Sword Art Online": '60.jpeg',
"61 Ansatsu Kyoushitsu 2nd season": '61.jpg',
"62 Ansatsu Kyoushitsu": '62.jpg',
"63 Chuunibyou demo Koi ga Shitai!": '63.jpg',
"64 Kimetsu no Yaiba": '64.jpg',
"65 Re:Zero kara Hajimeru Isekai Seikatsu": '65.jpg',
"66 Nanatsu no Taizai": '66.jpg',
"67 Steins;Gate 0": '67.jpeg',
"68 Steins;Gate": '68.jpeg',
"69 Nanatsu no Taizai: Imashime no Fukkatsu": '69.jpeg',
"70 Tokyo Ghoul √A": '70.jpeg',
"71 One Punch Man Season 2": '71.jpg',
"72 Hunter x Hunter (2011)": '72.jpeg',
"73 Darling in the FranXX": '73.jpg',
"74 Tokyo Ghoul": '74.jpeg',
"75 Boku no Hero Academia 3rd Season.": '75.jpg',
"76 Boku no Hero Academia": '76.jpg',
"77 Nanatsu no Taizai: Kamigami no Gekirin": '77.jpeg',
"78 Naruto": '78.jpeg',
"79 Boku no Hero Academia 4th Season": '79.jpeg',
"80 Arte": '80.jpeg',
"81 Yakusoku no Neverland": '81.jpeg',
"82 Aho Girl": '82.jpg',
"83 Wotaku ni Koi wa Muzukashii": '83.jpg',
"84 Kimi no Suizou wo Tabetai ": '84.jpeg',
"85 Sakasama no Patema": '85.jpg',
"86 Grisaia no Rakuen": '86.jpeg',
"87 Kimi ni Todoke": '87.jpeg',
"88 Kimi ni Todoke 2nd Season": '88.jpeg',
"89 Sukitte Ii na yo.": '89.jpg',
"90 Ore wo Suki nano wa Omae dake ka yo": '90.jpg',
"91 Koi To Uso": '91.jpeg',
"92 Saijaku Muhai no Bahamut": '92.jpg',
"93 7 seeds": '93.jpg',
"94 7 Seeds 2nd Season": '94.jpg',
"95 Kono Yo no Hate de Koi wo Utau Shoujo YU-NO": '95.jpg',
"96 Gotoubun no Hanayome": '96.jpg',
"97 Masamune-kun no Revenge": '97.jpg',
"98 Tokyo Magnitude 8.0": '98.jpeg',
"99 Keppeki Danshi! Aoyama-kun Episode ": '99.jpg',
"100  Ao Haru Ride": '100.jpg',
"101 Kakegurui": '101.jpeg',
"102 Kakegurui××": '102.jpg',
"103 Tokyo Ghoul:re": '103.jpg',
"104 Tokyo Ghoul:re 2nd season": '104.jpg',
"105 Toradora!": '105.jpg',
"106 Sounan Desu ka?": '106.jpg',
"107 Denpa Onna to Seishun Otoko": '107.jpg',
"108 Zenonzard The Animation": '108.jpg',
"109 Hanamaru Kindergarden": '109.jpg',
"110 Tonari no Kaibutsu-kun": '110.jpg',
"111 Domestic na Kanojo": '111.jpeg',
"112 Haikyuu!!": '112.jpg',
"113 Haikyuu!! Second Season": '113.jpg',
"114 Haikyuu!!: Karasuno Koukou vs. Shiratorizawa Gakuen Koukou": '114.jpeg',
"115 Haikyuu!!: To the Top": '115.jpg',
"116 Sword Art Online: Alicization – War of Underworld 2nd Season": '116.jpg',
"117 Haikyuu!!: To the Top": '117.jpg',
"118 Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan": '118.jpg',
"119 Kanojo, Okarishimasu": '119.jpg',
"120 Shokugeki no Souma: Gou no Sara": '120.jpg',
"121 Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e": '121.jpeg',
"122 UZAKI-CHAN WA ASOBITAI!": '122.jpeg',
"123 ReLIFE": '123.jpeg',
"124 ReLIFE: Kanketsu-hen": '124.jpg',
"125 The God of High School": '125.jpeg',
"126 Inou-Battle wa Nichijou-kei no Naka de": '126.jpeg',
"127 Kyoukai no Kanata": '127.jpeg',
"128 Arifureta Shokugyou de Sekai Saikyou": '128.jpg',
"129 ISEKAI MAOU TO SHOUKAN SHOUJO NO DOREI MAJUTSU": '129.jpeg',
"130 AKAME GA KILL!": '130.jpg',
"131 Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season": '131.jpg',
"132 Shinchou Yuusha: Kono Yuusha ga Ore Tueee Kuse ni Shinchou Sugiru": '132.jpg',
"133 Noragami": '133.jpeg',
"134 Noragami OVA": '134.jpg',
"135 Noragami Aragoto": '135.jpeg',
"136 Nisekoi": '136.jpeg',
"137 Nisekoi:": '137.jpg',
"138 Black Bullet": '138.jpg',
"139 Devils Line": '139.jpeg',
"140 TABOO TATTOO": '140.jpeg',
"141 Hajimete no Gal ": '141.jpg',
"142 Kuzu no Honkai": '142.jpg',
"143 Tsurezure Children": '143.jpg',
"144 Himouto! Umaru-chan": '144.jpg',
"145 Boku no Kanojo ga Majimesugiru Sho-bitch na Ken": '145.jpeg',
"146 Bungou Stray Dogs": '146.jpg',
"147 Bungou Stray Dogs Season 2": '147.jpg',
"148 Bungou Stray Dogs 3rd Season": '148.jpg',
"149 Lovely★Complex": '149.jpeg',
"150 Plunderer": '150.jpg',
"151 TONIKAKU KAWAII": '151.jpeg',
"152 Enen no Shouboutai: Ni no Shou": '152.jpg',
"153 Haikyuu!!: To the Top 2nd Season": '153.jpg',
"154 Shigatsu wa Kimi no Uso": '154.jpg',
"155 Kaichou wa Maid-sama": '155.jpg',
"156 Karakai Jouzu no Takagi-san": '156.jpg',
"157 Karakai Jouzu no Takagi-san 2": '157.jpg',
"158 Violet Evergarden": '158.png'
}

root = Tk()
root.geometry("200x100")

def fun():

    top = Toplevel(root)
    top.title('Anime')

    random_choice = random.choice(list(anime.keys())) #choosing random from dictionary keys
    
    label = Label(top, text=random_choice)
    label.pack()

    top.img = ImageTk.PhotoImage(Image.open(os.path.join(absolute_path.strip(),anime[random_choice])))
    
    image_label = Label(top, image=top.img)
    image_label.pack()

can = Canvas(root, height = 100, width = 100)
can.place(relx=0.5, rely=0.5, anchor=CENTER)

b1 = Button(can,text = "Generate",command = fun,activeforeground = "black",activebackground = "yellow",pady=10)
b1.pack(side = TOP)

root.mainloop()

